language: cpp
os: linux
dist: bionic

compiler:
    - gcc
    - clang

before_install:
    - sudo pip install conan

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=ON

script:
    - make
    - make test
    - bash <(curl -s https://codecov.io/bash)
